version: "2"

services:
    app:
        build: ./node
        container_name: "app"
        depends_on:
            - mqtt
        ports:
            - "80:80"
    mqtt:
        image: panuwitp/mosquitto-arm
        container_name: "mqtt"
        expose:
            - 1883
        ports:
            - "1883:1883"
