version: "2"

services:
    app:
        build: ./node
        container_name: "app"
        ports:
            - "80:80"
    mongo:
        image: mongo
        container_name: "db"
        expose:
            - 27017
        ports:
            - 27017:27017
    mqtt:
        image: panuwitp/mosquitto-arm
        container_name: "mqtt"
        expose:
            - 1883
        ports:
            - "1883:1883"
